<div style="background-color:#FFC0CB; padding:40px; text-align:center; border-radius:15px; color:black;">

<h1 style="font-size:40px; margin-bottom:20px; color:black;">
Práctica 1 - Introducción al uso de Python
</h1>

<h1 style="font-size:18px; color:black;">
Laboratorio de Bioseñales <br>
María Camila Tobón Úsuga
</h1>

</div>

In [4]:
import matplotlib
import numpy as np
import pandas

# Procedimiento

a. Creación de vectores a y b.

In [8]:
a = np.array([3.1,1, -0.5, -3.2, 6])
b = np.array([1, 3, 2.2, 5.1, 1])


b. Multiplicación escalar de vectores a y b. ¿Qué se debe hacer para implementar la multiplicación de los vectores?

Para poder hacer la multiplicación escalar, o también llamado producto punto de los dos vectores:

Ambos vectores deben de tener la misma longitud,se multiplica elemento a elemento y luego se efectua la suma de los resultados.

Para realizare esta operación se tiene la función np.dot o el operador @ de numpy.


In [11]:
c = np.dot(a, b)
print(c)
d= a @ b
print (d)

-5.32
-5.32


c. Multiplicacion punto a punto a a.b

In [12]:
e = a * b 
print(e)

[  3.1    3.    -1.1  -16.32   6.  ]


d. Construcción matriz A.

In [13]:
A= np.array([(2, -1, -3), (4, 1.5, -2.5), (7.3 , -0.9, 0.2)])

e. Transpuesta de A.

In [14]:
f= A.T
print(f)

[[ 2.   4.   7.3]
 [-1.   1.5 -0.9]
 [-3.  -2.5  0.2]]


f. Funciones librería Numpy. 

ones --> Devuelve una matriz de forma y tipo determinados, llena de unos.

np.ones(forma, tipo d=Ninguno como float o int, orden='C' para filas ó 'F' para columnas, como=para crear el arreglo con el mismo tipo que otro objeto)




In [24]:
g = np.ones((3,3), int)
print(g)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


round --> Redondear uniformemente al número dado de decimales.

np.round("a" el arreglo que se quiere modificar, decimales=0 número de deciamales a conservar, fuera= para guardar el resultado en una arreglo ya existente)

In [23]:
h = np.round(A, 0)
print(h)

[[ 2. -1. -3.]
 [ 4.  2. -2.]
 [ 7. -1.  0.]]


ceil --> Sirve para redondear cada número hacia arriba (al entero mayor más cercano), elemento por elemento.

np.ceil("x" arreglo a modificar, /, fuera=para guardar el resultado en una arreglo ya existente, *, donde=Permite aplicar la función solo en ciertas posiciones ejm x>0, casting='mismo_tipo', orden='K', dtype=Ninguno, subok=Verdadero[, firma])=<ufunc'ceil'>

In [30]:
i = np.ceil(A,None, where=A<0)
print(i)

[[ 2. -1. -3.]
 [ 4.  2. -2.]
 [ 8. -0.  1.]]
